import Link from "next/link";

const content = {
  home: { title: "Como preparar uma solicitação", paragraphs: ["Uma cotação útil começa com contexto suficiente para que a rota seja entendida sem suposições. Informe os dois endereços completos, o nome de quem entrega, o nome de quem recebe, o item e o horário desejado. Se houver portaria, doca, senha, assinatura, protocolo ou retorno, escreva tudo na primeira mensagem. A equipe consegue avaliar melhor quando não precisa reconstruir a missão por partes.", "A distância é apenas uma parte da decisão. Uma entrega curta pode ter acesso controlado e espera, enquanto uma rota mais longa pode ser direta. O valor publicado na página de preços serve como referência para trajetos simples; o atendimento confirma a condição aplicável à missão descrita. Essa transparência evita comparar serviços diferentes como se fossem iguais.", "A Moto11 atende de segunda a sexta, das 8h às 18h. Fora desse período, mensagens podem ficar para o próximo dia útil. Não há promessa automática de disponibilidade, prazo ou operação noturna. O caminho mais rápido para começar é usar o botão de WhatsApp, substituir os campos da mensagem e aguardar a confirmação antes de enviar o item."] },
  services: { title: "Escolha pelo tipo de missão", paragraphs: ["Documentos pedem atenção a sigilo, assinatura, protocolo e devolução. Pequenos volumes pedem peso, dimensão, embalagem e fragilidade. Coletas empresariais podem exigir janela, autorização, nota ou romaneio. Ao explicar a tarefa, você ajuda a equipe a indicar o formato mais adequado sem empurrar uma modalidade que não corresponde ao que precisa acontecer.", "Cartório, shopping e aeroporto não devem ser tratados como uma corrida comum. Acesso, estacionamento, balcão, credenciamento e espera podem mudar a execução. Por isso, esses destinos recebem cotação própria. O mesmo vale para missão com múltiplas paradas ou retorno: o roteiro completo precisa ser conhecido antes que o valor seja confirmado.", "Para contratar, envie origem, destino, item, contato nas duas pontas e prazo-limite. Se uma informação mudar depois da cotação, avise antes da saída. A proposta depende da missão descrita e da disponibilidade no momento, não apenas do nome do serviço escolhido."] },
  areas: { title: "Cobertura não é promessa automática", paragraphs: ["A página de áreas atendidas organiza bairros e referências para facilitar a descoberta do serviço. Ela não substitui o endereço completo. Rua, número, complemento, sentido da rota e horário são necessários para confirmar se a coleta pode ser realizada. Um bairro pode ter acessos e condições diferentes em pontos distintos.", "O atendimento considera Guarulhos e rotas para São Paulo sob consulta. Disponibilidade pode mudar conforme o horário, a demanda e as características do item. Se o bairro não aparecer na lista, envie os dois endereços assim mesmo. A avaliação deve ser feita pela rota real, não por uma promessa baseada somente em uma palavra-chave local.", "Use o hub para encontrar a região e depois siga para o WhatsApp ou contato. Informe se haverá portaria, espera, protocolo, assinatura ou retorno. Quanto mais clara a missão, mais fácil explicar valor e previsão antes da coleta."] },
  saoPaulo: { title: "Rotas entre municípios exigem contexto", paragraphs: ["Uma entrega entre Guarulhos e São Paulo envolve mais do que distância em mapa. O sentido da viagem, o ponto exato, o horário de recebimento, o trânsito e as regras do destino alteram a previsão. Por isso, as páginas de regiões servem como organização de consultas, enquanto a confirmação acontece com os endereços completos.", "Envie origem e destino sem abreviações, além do item e do horário-limite. Se houver compromisso com portaria, recepção, doca ou pessoa específica, descreva o procedimento. Para documentos, diga se existe assinatura ou protocolo; para encomendas, informe tamanho, peso e embalagem. Esses dados tornam a avaliação mais segura.", "A Moto11 atende em horário comercial, de segunda a sexta, das 8h às 18h. Não existe tempo universal para atravessar municípios. A estimativa deve ser confirmada no atendimento e não deve ser tratada como garantia quando depender de trânsito, chuva, bloqueio ou terceiros."] },
  map: { title: "Navegue pela informação certa", paragraphs: ["Este mapa organiza as páginas por tarefa. Comece por Serviços para entender modalidades, por Preços para consultar a regra publicada, por Áreas atendidas para explorar cobertura e por Contato para enviar a missão. FAQ reúne respostas rápidas; Sobre explica o modo de atendimento; os hubs de São Paulo tratam rotas metropolitanas.", "Links de bairros existem para consulta, mas páginas locais permanecem sob revisão editorial e não devem ser confundidas com garantia de disponibilidade. Páginas legais ficam disponíveis por transparência. URLs antigas podem redirecionar para uma página canônica quando o conteúdo anterior deixou de existir.", "O caminho recomendado é simples: leia o escopo, reúna origem, destino, item e horário, consulte a referência de preço e envie a rota pelo canal oficial. A confirmação final deve sempre considerar as condições reais da missão."] },
} as const;

export function EditorialSections({ variant }: { variant: keyof typeof content }) {
  const section = content[variant];
  return <section className="mx-auto max-w-3xl space-y-5 px-4 py-12 sm:px-6" aria-labelledby={`editorial-${variant}`}><h2 id={`editorial-${variant}`} className="font-display text-3xl font-bold text-brand-950">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="text-lg leading-8 text-muted">{paragraph}</p>)}<Link href="/contato" className="inline-flex min-h-12 items-center rounded-full bg-success px-6 py-3 font-bold text-white hover:bg-brand-900">Calcular orçamento</Link></section>;
}
